 services: 
   database: 
    image: postgres:18.3 
    restart: always 
    environment: 
      POSTGRES_PASSWORD: verySecretPassword 
      POSTGRES_USER: administrator 
      POSTGRES_DB: todo 
    volumes: 
      - ./data:/var/lib/postgresql 
